nodeExporter:
  enabled: true

prometheus:
  additionalScrapeConfigs:
    - job_name: 'trustvault-services'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: ['__meta_kubernetes_pod_label_app']
          regex: '(trustvault-.*)'
          action: keep
