{
 "title": "TrustVault Main",
 "tags": [ "trustvault" ],
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNonNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!='',pod=~'$service.*'}[5m])) by (pod) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage (24h)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container!='',pod=~'$service.*'}"
    }
   ]
  },
  {
   "title": "Alert Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(postgres_alerts_total[5m]))"
    }
   ]
  }
 ]
}