name: AI Service CI

on:
  push:
    branches:
      - main
      - dev
      - 'feat/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ai-service/requirements.txt ruff mypy coverage pytest
      - name: Lint
        run: ruff check ai_service
      - name: Lint (Auto-fix & fail on unfixable)
        run: pnpm run lint:fix -- --max-warnings 0
      - name: Type-check
        run: mypy ai_service --strict
      - name: Run tests
        run: |
          coverage run -m pytest -q
          coverage xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build local image
        uses: docker/build-push-action@v5
        with:
          context: ./ai-service
          file: ai-service/Dockerfile
          load: true
          tags: ai-service:local
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ai-service:local
          severity: CRITICAL,HIGH
      - name: Push image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./ai-service
          file: ai-service/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ai-service:sha-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/ai-service:latest
