name: TrustVault Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: npm ci
      - name: Install flake8
        run: pip install flake8
      - name: Lint JS
        run: npm run lint
      - name: Lint Python
        run: flake8 .

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: npm ci
      - name: Install pytest
        run: pip install pytest pytest-cov
      - name: Run unit tests (JS)
        run: npm test -- --coverage
      - name: Run unit tests (Python)
        run: pytest --maxfail=1 --disable-warnings --cov

  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Start app
        run: npm run dev &
      - name: Cypress run
        run: npx cypress run

  performance-tests:
    needs: [e2e-tests]
    runs-on: ubuntu-latest
    env:
      TARGET_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v4
      - name: Install k6
        run: sudo apt-get update && sudo apt-get install -y k6
      - name: Run k6 load test
        run: k6 run --out json=load-test-result.json deployment/tests/load-test.js
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: load-test-result
          path: load-test-result.json

  build:
    runs-on: ubuntu-latest
    needs: performance-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build
      - name: Build backend image
        run: docker build -t trustvault-api ./api

