name: Security & Compliance Audit

on:
  push:
    branches: [main, dev]

jobs:
  ui-accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm ci
          npm install puppeteer @axe-core/puppeteer
      - name: Run axe-core accessibility tests
        env:
          UI_URL: ${{ secrets.UI_URL }}
        run: node deployment/tests/audit-ui.js

  ledger-tamper:
    runs-on: ubuntu-latest
    needs: ui-accessibility
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: trustvault
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install pytest psycopg2-binary
      - name: Run tamper test
        env:
          DATABASE_URL: postgres://user:pass@localhost:5432/trustvault
        run: pytest deployment/tests/tamper_test.py -q
