name: Container Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build trustvault-api image
        run: docker buildx build --load -t trustvault-api:latest ./api
      - name: Build ai-service image
        run: docker buildx build --load -t ai-service:latest ./ai-service
      - name: Build soar-service image
        run: docker buildx build --load -t soar-service:latest ./soar-service
      - name: Build ledger-service image
        run: docker buildx build --load -t ledger-service:latest ./ledger-service
      - name: Build iam-service image
        run: docker buildx build --load -t iam-service:latest ./iam-service

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: aquasecurity/trivy-action@v0.9.0
        with:
          image-ref: trustvault-api:latest
          severity: HIGH,CRITICAL
          exit-code: '1'
      - uses: aquasecurity/trivy-action@v0.9.0
        with:
          image-ref: ai-service:latest
          severity: HIGH,CRITICAL
          exit-code: '1'
      - uses: aquasecurity/trivy-action@v0.9.0
        with:
          image-ref: soar-service:latest
          severity: HIGH,CRITICAL
          exit-code: '1'
      - uses: aquasecurity/trivy-action@v0.9.0
        with:
          image-ref: ledger-service:latest
          severity: HIGH,CRITICAL
          exit-code: '1'
      - uses: aquasecurity/trivy-action@v0.9.0
        with:
          image-ref: iam-service:latest
          severity: HIGH,CRITICAL
          exit-code: '1'
