name: Token Revoker CI

on:
  push:
    branches: [main, dev, 'feat/**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'   # ≥ 1.23 to satisfy go.mod
          check-latest: true
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Lint
        run: make -C iam-service/cmd/token-revoker lint
      - name: Test
        run: make -C iam-service/cmd/token-revoker test
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./iam-service
          file: iam-service/cmd/token-revoker/Dockerfile
          load: true
          tags: token-revoker:local
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: token-revoker:local
          severity: CRITICAL,HIGH
