openapi: 3.0.0
info:
  title: API Gateway
  version: 1.0.0
paths:
  /health:
    get:
      summary: Healthcheck
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /alerts:
    get:
      summary: Alerts proxy
      responses:
        '200':
          description: OK
